const SET_RANDOM_ACTIVITY_ALL = "SET_RANDOM_ACTIVITY_ALL";
const SET_RANDOM_COUPLES = "SET_RANDOM_COUPLES";
const SET_RANDOM_CRAFTS = "SET_RANDOM_CRAFTS";
const SET_RANDOM_FAMILY = "SET_RANDOM_FAMILY";
const SET_RANDOM_WELLNESS = "SET_RANDOM_WELLNESS";
const SET_RANDOM_FOOD = "SET_RANDOM_FOOD";
const SET_RANDOM_INSIDE = "SET_RANDOM_INSIDE";
const SET_RANDOM_OUTSIDE = "SET_RANDOM_OUTSIDE";
const SET_RANDOM_PROJECTS = "SET_RANDOM_PROJECTS";
const SET_RANDOM_SOLO = "SET_RANDOM_SOLO";
const CLEAR_SELECTED_ACTIVITY = "CLEAR_SELECTED_ACTIVITY";
const NEXT_ACTIVITY = "NEXT_ACTIVITY";

export {
  SET_RANDOM_ACTIVITY_ALL,
  SET_RANDOM_COUPLES,
  SET_RANDOM_CRAFTS,
  SET_RANDOM_FAMILY,
  SET_RANDOM_WELLNESS,
  SET_RANDOM_FOOD,
  SET_RANDOM_INSIDE,
  SET_RANDOM_OUTSIDE,
  SET_RANDOM_PROJECTS,
  SET_RANDOM_SOLO,
  CLEAR_SELECTED_ACTIVITY,
  NEXT_ACTIVITY,
};
