const SET_RANDOM_ACTIVITY_ALL = "SET_RANDOM_ACTIVITY_ALL"
const SET_RANDOM_COUPLES = 'SET_RANDOM_COUPLES'
const SET_RANDOM_CRAFTS = 'SET_RANDOM_CRAFTS'

const CLEAR_SELECTED_ACTIVITY = "CLEAR_SELECTED_ACTIVITY"

export {
    SET_RANDOM_ACTIVITY_ALL,
    SET_RANDOM_COUPLES,
    SET_RANDOM_CRAFTS,


    CLEAR_SELECTED_ACTIVITY
}