const SET_RANDOM_ACTIVITY_ALL = "SET_RANDOM_ACTIVITY_ALL"
const SET_RANDOM_COUPLES = 'SET_RANDOM_COUPLES'

const CLEAR_SELECTED_ACTIVITY = "CLEAR_SELECTED_ACTIVITY"

export {
    SET_RANDOM_ACTIVITY_ALL,
    SET_RANDOM_COUPLES,
    CLEAR_SELECTED_ACTIVITY
}